name: onechat
description: "A new Flutter project."
publish_to: 'none'
version: 2.5.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_contacts: ^1.1.9+2
  permission_handler: ^11.3.1
  sqflite: ^2.3.0
  path: ^1.9.0
  flutter_secure_storage: ^10.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Ensure assets are indented 2 spaces under 'flutter'
  assets:
    - assets/images/splash.png

  # Ensure fonts are indented 2 spaces under 'flutter'
  fonts:
    - family: Barrio
      fonts:
        - asset: assets/fonts/Barrio-Regular.ttf
    - family: FontDiner
      fonts:
        - asset: assets/fonts/FontdinerSwanky-Regular.ttf

# Configuration for the launcher icons package
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo/icon.png"
